---
- hosts: 
  become: yes
  become_user: n90xxxx "user which is used to login to Satellite GUI"
  tasks:
   - name: Run the script
     script: /etc/ansible/patching/RFC/RFC-done/RFC87419-Prod_AEM_CQ_Site_A/registerservers.sh
